baseURL = "https://netscope-oversight.pages.dev/"
title = "Netscope-oversight"
theme = "PaperMod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
ShowShareButtons = true
ShowReadingTime = true
defaultTheme = "auto"

[markup.goldmark.renderer]
unsafe = true

