baseURL = "https://netscope-oversight.pages.dev/"
title = "Netscope-oversight"
theme = "PaperMod"

[params]
  ShowShareButtons = false
  ShowReadingTime = true
  defaultTheme = "auto"
  search = true
  ShowPostNavLinks = true
  
[params.cover]
  responsiveImages = false

[params.profileMode]
  enabled = true
  title = "Netscope Oversight"
  subtitle = "Network - Art - Communism"
  imageUrl = "/img/me-smoke.jpg"
  imageTitle = "Profilbild"
  imageWidth = 120
  imageHeight = 120

 # [[params.profileMode.buttons]]
 #   name = "Archive"
 #   url = "/archive"

 # [[params.profileMode.buttons]]
 #   name = "Posts"
 #   url = "/posts/"

 # [[params.profileMode.buttons]]
 # name = "Search"
 # url = "/search/"

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/Babayaga069"

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://www.instagram.com/shindy"

  # [[params.socialIcons]]
  #  name = "LinkedIn"
  #  url = "https://linkedin.com/in/deinprofil"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 10

  [[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 20

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30
